### ISSUE TITLE
Known bugs

### ISSUE THREAD

**Issue by ZM-J** [prunusnira/piumanager#2]
### 1. For example, when I choose 'S14' category and mark a song to be a 'blue A', then change 'S15' category, the statistics could be wrong.
(If I have changed something in 'S15', it works, but if 'S15' is new, it doesn't change and still shows statistics from 'S14')
```
SSS: 0 | SS: 1 | S: 0 | A: 32 | BCD: 0
A: 4 (Off) | BCD: 1 (Off) | F: 0 | No Play: 30
```
I think the issue may be from `piumanager/src/piutable/piutable.tsx`, and it may be related to [PIUTable.state.rankxxx](https://github.com/prunusnira/piumanager/blob/master/src/piutable/piutable.tsx#L142). An additional call of [PIUTable.updateRankData](https://github.com/prunusnira/piumanager/blob/master/src/piutable/piutable.tsx#L624) should be applied when receiving a category choosing request.

### 2. When I load information of a user, and then choose 'New User', the previous user information (records) is not reset.

**Comment by prunusnira** [comment]
Thanks for the report. I will check and fix problems

**Comment by prunusnira** [comment]
for 2, I added modal message for reset user data.
it will be updated in next update

currently working on load and 1
